server:
  port: 9090

spring:
  application:
    name: apiGateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: one-service
              uri: http://localhost:8080
              predicates:
                - Path=/one/api/auth/**
              filters:
                - StripPrefix=1
            - id: two-service
              uri: http://localhost:8080
              predicates:
                - Path=/two/api/auth/**
              filters:
                - StripPrefix=1

# Actuator endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# Logging configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO